services:
  babambu-wled-api:
    image: <your-dockerhub-username>/bambu-wled-api:latest
    ports:
      - '3000:3000'
    restart: always
    environment:
      - HASS_URL=${HASS_URL}
      - HASS_TOKEN=${HASS_TOKEN}
      - WLED_URL=${WLED_URL}
      - EVENT_PRINTER_SERIAL_NUMBER=${EVENT_PRINTER_SERIAL_NUMBER}
