services:
  wled-bambu-status:
    container_name: wled-bambu-status
    image: node:20
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - HASS_URL=${HASS_URL}
      - HASS_TOKEN=${HASS_TOKEN}
      - WLED_URL=${WLED_URL}
      - EVENT_PRINTER_SERIAL_NUMBER=${EVENT_PRINTER_SERIAL_NUMBER}
    command: ['npm', 'run', 'start']
